### ISSUE TITLE
Updated Influitive and Powered By Logos

### ISSUE THREAD

**Issue by MattInfluitive** [influitive/patternity#12]
![influitive_logo_tag_white](https://cloud.githubusercontent.com/assets/10437489/6925289/6dbe26c0-d7ac-11e4-9b6a-c378a903730d.png)
![influitive_logo_tag](https://cloud.githubusercontent.com/assets/10437489/6925290/6dbfd876-d7ac-11e4-863f-263e160cebc7.png)
![influitive_logo_white](https://cloud.githubusercontent.com/assets/10437489/6925291/6dc07f1a-d7ac-11e4-9db3-c27ea4a72888.png)
![influitive_logo](https://cloud.githubusercontent.com/assets/10437489/6925288/6dbdf90c-d7ac-11e4-8267-74d5f8b334d9.png)
![powered_by](https://cloud.githubusercontent.com/assets/10437489/6925287/6dbde110-d7ac-11e4-8467-9f24918952c0.png)

**Comment by dsteinman** [comment]
this is now center aligned
