### ISSUE TITLE
Modal UI Polish

### ISSUE THREAD

**Issue by MattInfluitive** [influitive/patternity#26]
Gave the modals you made a quick UI once over. Mostly just gave them some more space. (The larger one is on a 50% black lightbox)
Let me know if the mockup with the different padding/spacing is too much or if it's not clear what's going on. I think the spacing can stay the same for the S/M/L sizes, just the content can expand.

![screen shot 2015-04-14 at 4 35 54 pm](https://cloud.githubusercontent.com/assets/10437489/7147233/94578b2a-e2c7-11e4-8249-fbdbaf646cb0.png)

![screen shot 2015-04-14 at 4 37 41 pm](https://cloud.githubusercontent.com/assets/10437489/7147236/97382c6e-e2c7-11e4-9dc8-ed5fdb512a01.png)

**Comment by bradrobertson** [comment]
The 'X' to close the modal feels a bit large IMO. Kind of looks comical
