### ISSUE TITLE
pills

### ISSUE THREAD

**Issue by desheikh** [influitive/patternity#46]
A number of areas on the hub use a pill version of tabs. We can remove the default tab/pill styling once patternity supports pills.

https://app.influitiveqa.com/challenges
https://app.influitiveqa.com/contacts/1 -> Edit Profile

**Comment by nickfaulkner** [comment]
we are depreciating this pattern from the hub and will not be adding it to patternity.  as we update pages we will convert that tab pills to being the patternity tabs.
