### ISSUE TITLE
TextInput - we need an autofocus option for TextInput

### ISSUE THREAD

**Issue by mikestok** [influitive/patternity#48]
Something like

```jsx
<TextInput autofocus={true} />
```

Which would automatically set the focus on the input element.

I think this can be achieved with `componentDidUpdate` by grabbing the ref calling focus

```javascript
componentDidUpdate: function () {
  this.refs.theInputRef.getDOMNode().focus();
}
```
Or something.

**Comment by bradrobertson** [comment]
Should probably be:

```javascript
componentDidMount: function () {}
```

Instead.
