### ISSUE TITLE
small discrepancy between <a class='button'.. and <input type='submit' class='button'..

### ISSUE THREAD

**Issue by desheikh** [influitive/patternity#51]
![image](https://cloud.githubusercontent.com/assets/27354/7542690/eee161a6-f58c-11e4-837e-2c5273025454.png)

**Comment by desheikh** [comment]
Sample page app.influitiveqa.com/corporate/settings/email/day_after_joined

**Comment by nickfaulkner** [comment]
this is a chrome specific issue.  still trying to find a solution that fixes the root of the issue, without browser specific hacks
