### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by nickfaulkner** [influitive/patternity#58]
We need to make a button component to handle all the types of styling a button can have, a long with the ability to make icon buttons, such as "+ Add Item" etc.

**Comment by daninfluitive** [comment]
<Button> was already done:

http://patternity.internal.influitive.com/?p=atoms-buttons

**Comment by nickfaulkner** [comment]
we need to clean it up a bit as it still takes className and then handles primary and secondary as a special case.

**Comment by daninfluitive** [comment]
I wouldn't make the className property because you wouldn't be able to apply additional css to buttons, like align or float them.

**Comment by nickfaulkner** [comment]
i'd rather add a wrapper that handles that styling for you... also i want avoid people adding custom button colours and styles.  we have set specific buttons and designs for a reason.  if we need a new button styling it should come from design, and then be added.

we want to keep these buttons as consistent in style and how we use them.

**Comment by daninfluitive** [comment]
Why it's a problem at all to use a CSS class name?  I'm just completely not understanding what the reason is.
