### ISSUE TITLE
Ability to use darker/lighter versions of the color palette through vars

### ISSUE THREAD

**Issue by desheikh** [influitive/patternity#84]
It would be nice to have $info-color-lighter/$info-color-darker or maybe $info-color-border/$info-color-shadow.

Basically just the alternate versions of the default color so people don't end up doing things like this in the app:
border-color: darken($success-color, 10%);

**Comment by daninfluitive** [comment]
Added 10% variations for all the alter colors:

https://github.com/influitive/patternity/commit/bb573491cd379f5dba757d25dc4023d3698a63d9
